In [1]:
import pandas as pd

In [2]:
file = "resource/SDCCD-Prop-S-N-Closeout-Checklist.xlsx"

In [3]:
file_df = pd.read_excel(file)
file_df.head(5)

,P,Campus,ProjectNumber,FUSION #,ProjectDescription,DSA,DSANumber,LEED,LEEDTarget,RecordDrawings,...,S - Ballot Reference #,N - Ballot Reference #,On Both Ballots,Unnamed: 74,Unnamed: 75,Proj #,Unnamed: 77,DSA_Count,LEED_Count,GIS_Count
NaN,N,City,11110,NaN,Humanities Building,Yes,04-110503,No,"Gold (still ""in progress"" 9/23/19)",Yes,...,S.I.2,N.II.1,x,NaN,NaN,11110,NaN,1.0,1.0,1.0
NaN,N,City,11240,NaN,Business Technology Building,Yes,04-110503,No,"Gold (still ""in progress"" 9/23/19)",Yes,...,S.I.3,N.I.3,x,NaN,NaN,11240,NaN,1.0,1.0,1.0
NaN,N,City,11250,NaN,"Engineering Technology Building (""T"" Building)",Yes,04-114494,Yes,Gold (62 points) achieved March 2019,Yes,...,S.I.1,N.I.2,x,NaN,NaN,11250,NaN,1.0,1.0,1.0
NaN,N,City,11260,NaN,Science Building,No,04-111042 (certified); 04-117766 (Alts to Scie...,Yes,Silver,Yes,...,S.IV (?),N.I.1,x,NaN,NaN,11260,NaN,1.0,1.0,1.0
NaN,N,City,11310,NaN,"""M"" Classroom Building",Yes,04-112843,Yes,Silver,Yes,...,S.IV.1,N.III.3,x,NaN,NaN,11310,NaN,1.0,1.0,1.0

In [4]:
file_df.to_csv("output/SDCCD-Program-Close-Data.csv", index=False, header=True)